"""relevant nullable for redash days

Revision ID: 11a50e20a20b
Revises: da97f2dfabb6
Create Date: 2026-10-07 10:30:05.858442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a50e20a20b'
down_revision: Union[str, Sequence[str], None] = 'da97f2dfabb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program_registrations', 'relevant',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program_registrations', 'relevant',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
