"""redash event window

Revision ID: 612fbfda5ff5
Revises: 6203af446889
Create Date: 2026-10-07 11:47:00.264388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612fbfda5ff5'
down_revision: Union[str, Sequence[str], None] = '6203af446889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_registration_settings', sa.Column('redash_event_start', sa.Date(), nullable=True))
    op.add_column('program_registration_settings', sa.Column('redash_event_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_registration_settings', 'redash_event_end')
    op.drop_column('program_registration_settings', 'redash_event_start')
    # ### end Alembic commands ###
