"""add app-authored note support to program_notes

Revision ID: 7b3a85775d8b
Revises: b1718bedb6e3
Create Date: 2026-09-28 15:52:32.254519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3a85775d8b'
down_revision: Union[str, Sequence[str], None] = 'b1718bedb6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_notes', sa.Column('author_name', sa.String(), nullable=True))
    op.add_column('program_notes', sa.Column('source', sa.String(), server_default=sa.text("'hubspot'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_notes', 'source')
    op.drop_column('program_notes', 'author_name')
    # ### end Alembic commands ###
