"""add redash settings to registration settings

Revision ID: 89088fe6f0d4
Revises: af15727fc3b0
Create Date: 2026-10-01 20:15:11.878458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89088fe6f0d4'
down_revision: Union[str, Sequence[str], None] = 'af15727fc3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_registration_settings', sa.Column('redash_auto', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('program_registration_settings', sa.Column('redash_query_id', sa.String(), nullable=True))
    op.add_column('program_registration_settings', sa.Column('redash_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_registration_settings', 'redash_params')
    op.drop_column('program_registration_settings', 'redash_query_id')
    op.drop_column('program_registration_settings', 'redash_auto')
    # ### end Alembic commands ###
