"""create programs and sync_cursors tables

Revision ID: 8c133b467dfb
Revises: 
Create Date: 2026-09-25 19:59:05.595200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c133b467dfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('pipeline_label', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('stage_label', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('other_event_name', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('registration_start_date', sa.Date(), nullable=True),
    sa.Column('event_end_date', sa.Date(), nullable=True),
    sa.Column('target_audience', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('geography', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('blackops_account_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('csm_for_the_deal', sa.String(), nullable=True),
    sa.Column('account_manager', sa.String(), nullable=True),
    sa.Column('internal_team', sa.String(), nullable=True),
    sa.Column('expected_deal_size', sa.Double(), nullable=True),
    sa.Column('pre_sales_status', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('onboarding_status', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ongoing_status', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('post_campaign_status', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('stage_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('ticket_validity', sa.String(), nullable=True),
    sa.Column('final_resolution', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('stage_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_programs_created_at'), 'programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_programs_last_modified_at'), 'programs', ['last_modified_at'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_programs_last_modified_at'), table_name='programs')
    op.drop_index(op.f('ix_programs_created_at'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
