"""add program registrations and slack settings

Revision ID: af15727fc3b0
Revises: 3b96137f8397
Create Date: 2026-09-30 13:53:17.792765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af15727fc3b0'
down_revision: Union[str, Sequence[str], None] = '3b96137f8397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_registration_settings',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('fields', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('slack_channel_id', sa.String(), nullable=True),
    sa.Column('slack_channel_name', sa.String(), nullable=True),
    sa.Column('notify_slack', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['programs.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('program_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('role', sa.String(), server_default='', nullable=False),
    sa.Column('registrations', sa.Integer(), nullable=False),
    sa.Column('relevant', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['programs.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'date', 'role', name='uq_program_registrations')
    )
    op.create_index(op.f('ix_program_registrations_ticket_id'), 'program_registrations', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_registrations_ticket_id'), table_name='program_registrations')
    op.drop_table('program_registrations')
    op.drop_table('program_registration_settings')
    # ### end Alembic commands ###
