"""add provenance, stage history, notes, and resolved poc/account-manager/csm owners

Revision ID: b1718bedb6e3
Revises: 8c133b467dfb
Create Date: 2026-09-25 20:23:42.677049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1718bedb6e3'
down_revision: Union[str, Sequence[str], None] = '8c133b467dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_notes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['programs.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_program_notes_ticket_id'), 'program_notes', ['ticket_id'], unique=False)
    op.create_table('program_stage_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['programs.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'property_name', 'changed_at', name='uq_program_stage_history')
    )
    op.create_index(op.f('ix_program_stage_history_ticket_id'), 'program_stage_history', ['ticket_id'], unique=False)
    op.add_column('programs', sa.Column('account_manager_id', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('account_manager_name', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('csm_id', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('csm_name', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('content_poc_id', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('content_poc_name', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('record_source', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('record_source_detail', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('num_notes', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('notes_last_updated', sa.DateTime(), nullable=True))
    op.add_column('programs', sa.Column('raw_properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('programs', sa.Column('first_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('programs', sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('programs', 'csm_for_the_deal')
    op.drop_column('programs', 'account_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('account_manager', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('programs', sa.Column('csm_for_the_deal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('programs', 'last_synced_at')
    op.drop_column('programs', 'first_synced_at')
    op.drop_column('programs', 'raw_properties')
    op.drop_column('programs', 'notes_last_updated')
    op.drop_column('programs', 'num_notes')
    op.drop_column('programs', 'record_source_detail')
    op.drop_column('programs', 'record_source')
    op.drop_column('programs', 'updated_by_user_id')
    op.drop_column('programs', 'created_by_user_id')
    op.drop_column('programs', 'content_poc_name')
    op.drop_column('programs', 'content_poc_id')
    op.drop_column('programs', 'csm_name')
    op.drop_column('programs', 'csm_id')
    op.drop_column('programs', 'account_manager_name')
    op.drop_column('programs', 'account_manager_id')
    op.drop_index(op.f('ix_program_stage_history_ticket_id'), table_name='program_stage_history')
    op.drop_table('program_stage_history')
    op.drop_index(op.f('ix_program_notes_ticket_id'), table_name='program_notes')
    op.drop_table('program_notes')
    # ### end Alembic commands ###
