"""add platform_details to programs

Revision ID: c898e9307afe
Revises: d6c65373f2c5
Create Date: 2026-09-29 19:58:03.170438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c898e9307afe'
down_revision: Union[str, Sequence[str], None] = 'd6c65373f2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('platform_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'platform_details')
    # ### end Alembic commands ###
