"""add program documents, progress and deal size source

Revision ID: c8b5492f2997
Revises: e6e381ee997e
Create Date: 2026-09-29 13:49:28.223097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8b5492f2997'
down_revision: Union[str, Sequence[str], None] = 'e6e381ee997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_document_progress',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['programs.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'kind', 'item_key')
    )
    op.create_table('program_documents',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('hubspot_property', sa.String(), nullable=False),
    sa.Column('hubspot_file_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['programs.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'kind')
    )
    op.add_column('programs', sa.Column('deal_size_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'deal_size_source')
    op.drop_table('program_documents')
    op.drop_table('program_document_progress')
    # ### end Alembic commands ###
