"""drop program_document_progress

Revision ID: d6c65373f2c5
Revises: c8b5492f2997
Create Date: 2026-09-29 14:04:49.262988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6c65373f2c5'
down_revision: Union[str, Sequence[str], None] = 'c8b5492f2997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_document_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_document_progress',
    sa.Column('ticket_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['programs.ticket_id'], name=op.f('program_document_progress_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'kind', 'item_key', name=op.f('program_document_progress_pkey'))
    )
    # ### end Alembic commands ###
