"""redash event slug replaces query id and params

Revision ID: da97f2dfabb6
Revises: 89088fe6f0d4
Create Date: 2026-10-01 20:25:59.826515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da97f2dfabb6'
down_revision: Union[str, Sequence[str], None] = '89088fe6f0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_registration_settings', sa.Column('redash_event_slug', sa.String(), nullable=True))
    op.drop_column('program_registration_settings', 'redash_query_id')
    op.drop_column('program_registration_settings', 'redash_params')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_registration_settings', sa.Column('redash_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('program_registration_settings', sa.Column('redash_query_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('program_registration_settings', 'redash_event_slug')
    # ### end Alembic commands ###
